export const GLOSSARY = [
  {
    term: "BDNF",
    full: "Brain-Derived Neurotrophic Factor",
    emoji: "🌱",
    color: "#22c55e",
    def: "A protein that acts like fertilizer for neurons — it promotes growth, strengthening, and survival of brain cells. Depression depletes it (hippocampus physically shrinks). Antidepressants restore BDNF production over weeks, literally growing new synaptic connections.",
    related: ["Neuroplasticity", "Hippocampus", "Synapse"],
  },
  {
    term: "SERT",
    full: "Serotonin Transporter",
    emoji: "🅿️",
    color: "#f0abfc",
    def: "A protein on presynaptic neurons that acts like a vacuum — it sucks serotonin back out of the synapse after release, stopping its effect. Vortioxetine (and all SSRIs) block SERT, keeping serotonin active longer between neurons.",
    related: ["Serotonin", "Synapse", "Reuptake"],
  },
  {
    term: "CYP2D6",
    full: "Cytochrome P450 2D6",
    emoji: "🚰",
    color: "#a78bfa",
    def: "A liver enzyme responsible for metabolizing (breaking down) vortioxetine. When CYP2D6 is inhibited by Wellbutrin or fluoxetine, Trintellix clears more slowly — effectively making each dose stronger. ~2.1× boost from Wellbutrin alone.",
    related: ["Metabolism", "Wellbutrin", "Fluoxetine"],
  },
  {
    term: "Vortioxetine",
    full: "Trintellix — generic name",
    emoji: "💊",
    color: "#06b6d4",
    def: "The generic name for Trintellix. A 'multimodal' antidepressant that works via SERT inhibition PLUS direct agonism/antagonism at 5 serotonin receptor subtypes (5-HT1A, 5-HT1B, 5-HT1D, 5-HT3, 5-HT7). Unlike plain SSRIs, this multimodal action drives cognitive improvement and emotional flexibility.",
    related: ["SERT", "5-HT3", "5-HT1A", "5-HT7"],
  },
  {
    term: "5-HT3",
    full: "Serotonin 3 Receptor",
    emoji: "🔊",
    color: "#f97316",
    def: "A serotonin receptor subtype on GABAergic interneurons. When active, it tells GABA neurons to fire — silencing glutamate, dopamine, and acetylcholine circuits. Trintellix blocks 5-HT3, releasing the 'mute' on cognition. This is the primary mechanism behind the cognitive clarity effect.",
    related: ["GABA", "Glutamate", "Dopamine", "Cognition"],
  },
  {
    term: "5-HT1A",
    full: "Serotonin 1A Receptor",
    emoji: "🔑",
    color: "#22d3ee",
    def: "Found both as autoreceptors (in raphe nuclei — the 'thermostat') and as postsynaptic receptors. Trintellix is a partial agonist here. Postsynaptic 5-HT1A activation drives anxiolytic effects and emotional flexibility. Autoreceptor activity contributes to the initial negative feedback that delays antidepressant onset.",
    related: ["Autoreceptor", "Raphe Nuclei", "Anxiolytic"],
  },
  {
    term: "5-HT7",
    full: "Serotonin 7 Receptor",
    emoji: "🕐",
    color: "#818cf8",
    def: "Controls circadian rhythm and REM sleep architecture. Trintellix antagonizes 5-HT7, gradually restructuring sleep — deeper slow-wave sleep, normalized REM. Better sleep feeds BDNF production and glymphatic clearance.",
    related: ["Circadian Rhythm", "REM", "Glymphatic"],
  },
  {
    term: "Autoreceptor",
    full: "Presynaptic Serotonin Autoreceptor",
    emoji: "🛑",
    color: "#22d3ee",
    def: "A self-sensing receptor on the serotonin-releasing neuron itself (in the raphe nuclei). When it detects too much serotonin, it slams the brakes on further release. This is why antidepressants take 2-4 weeks — autoreceptors must desensitize (stop braking) before the full therapeutic increase in serotonin firing occurs.",
    related: ["Raphe Nuclei", "5-HT1A", "Desensitization"],
  },
  {
    term: "Raphe Nuclei",
    full: "Dorsal & Median Raphe Nuclei",
    emoji: "⚡",
    color: "#fbbf24",
    def: "The brain's primary serotonin-producing region, located in the brainstem. Nearly all serotonergic neurons project from here throughout the brain. Autoreceptor desensitization in the raphe is the critical rate-limiting step for antidepressant onset.",
    related: ["Autoreceptor", "Serotonin", "Brainstem"],
  },
  {
    term: "DMN",
    full: "Default Mode Network",
    emoji: "🧠",
    color: "#fbbf24",
    def: "A brain circuit most active during rest — responsible for self-referential thinking, mind-wandering, and rumination. In depression, DMN is hyperconnected, making negative thought loops sticky and hard to escape. Trintellix gradually normalizes DMN connectivity over weeks 5-8.",
    related: ["Rumination", "Neuroplasticity", "BDNF"],
  },
  {
    term: "Glymphatic System",
    full: "Glymphatic Clearance System",
    emoji: "🚿",
    color: "#fb7185",
    def: "The brain's waste disposal system. During deep sleep, CSF flows through channels (aquaporin-4 water channels) around neurons, flushing out metabolic debris including amyloid-beta and tau. Depression impairs this system. Trintellix restores it at 8+ weeks (per 2025 research), improving cognitive clarity.",
    related: ["Aquaporin-4", "Deep Sleep", "5-HT7"],
  },
  {
    term: "GABA",
    full: "Gamma-Aminobutyric Acid",
    emoji: "🔇",
    color: "#f97316",
    def: "The brain's primary inhibitory neurotransmitter — it quiets neural activity. In the context of Trintellix, 5-HT3 blockade prevents GABA interneurons from firing, which paradoxically increases cognition by disinhibiting glutamate, dopamine, and acetylcholine circuits.",
    related: ["5-HT3", "Glutamate", "Disinhibition"],
  },
  {
    term: "Glutamate",
    full: "Glutamate (Excitatory Neurotransmitter)",
    emoji: "⚡",
    color: "#22c55e",
    def: "The brain's primary excitatory neurotransmitter. Important for learning, memory, and cognition. When GABA disinhibition occurs via 5-HT3 blockade, glutamate circuits fire more freely — contributing to the 'mental sharpness' effect of Trintellix.",
    related: ["GABA", "5-HT3", "AMPA Receptor"],
  },
  {
    term: "Norfluoxetine",
    full: "Active Fluoxetine Metabolite",
    emoji: "⏳",
    color: "#ef4444",
    def: "The primary active metabolite of fluoxetine (Prozac) with an extremely long half-life of ~9 days (vs Prozac's 1-6 days). When switching from Prozac, norfluoxetine lingers for weeks, providing some SERT coverage during the transition — and inhibiting CYP2D6, boosting vortioxetine levels.",
    related: ["Fluoxetine", "CYP2D6", "Half-life"],
  },
  {
    term: "Half-life (t½)",
    full: "Pharmacokinetic Half-life",
    emoji: "⏱",
    color: "#94a3b8",
    def: "The time for a drug's concentration to halve. Vortioxetine t½≈66h (reaches steady state in ~2 weeks). Fluoxetine t½≈48h. Norfluoxetine t½≈9 days. CYP2D6 inhibition lengthens effective half-life by slowing breakdown.",
    related: ["Steady State", "CYP2D6", "Norfluoxetine"],
  },
  {
    term: "Steady State",
    full: "Pharmacokinetic Steady State",
    emoji: "📊",
    color: "#06b6d4",
    def: "When drug intake rate equals elimination rate — plasma concentration stabilizes. Takes ~5 half-lives. For vortioxetine (~66h t½), full steady state is reached ~2 weeks after starting. CYP2D6 inhibition from Wellbutrin means effective steady state is higher than the dose label alone suggests.",
    related: ["Half-life", "CYP2D6", "SERT"],
  },
  {
    term: "Neuroplasticity",
    full: "Synaptic Neuroplasticity",
    emoji: "🔀",
    color: "#22c55e",
    def: "The brain's ability to reorganize by forming new connections between neurons (or pruning unused ones). Depression impairs plasticity. BDNF is the key molecular driver of plasticity. Antidepressants restore plasticity over weeks 4-8, enabling the 'rewiring' that underlies lasting mood improvement.",
    related: ["BDNF", "Synapse", "DMN"],
  },
  {
    term: "Synapse",
    full: "Synaptic Cleft",
    emoji: "🔬",
    color: "#a78bfa",
    def: "The tiny gap between two neurons where neurotransmitters are released. Serotonin is released into the synapse, binds to receptors on the next neuron, then gets sucked back up by SERT. Antidepressants increase synaptic serotonin concentration by blocking this reuptake.",
    related: ["SERT", "Serotonin", "Reuptake"],
  },
  {
    term: "Reuptake",
    full: "Neurotransmitter Reuptake",
    emoji: "↩️",
    color: "#94a3b8",
    def: "The process where a neuron recycles its neurotransmitters by sucking them back in after release. SERT is the reuptake transporter for serotonin. SSRIs and SNRIs work by blocking this process (reuptake inhibition), keeping serotonin in the synapse longer.",
    related: ["SERT", "Synapse", "Serotonin"],
  },
  {
    term: "PK",
    full: "Pharmacokinetics",
    emoji: "📈",
    color: "#06b6d4",
    def: "What the body does to the drug — absorption, distribution, metabolism, excretion. Covers plasma levels, half-life, CYP2D6 effects, and receptor occupancy. PK effects kick in within hours to days.",
    related: ["PD", "CYP2D6", "Half-life", "SERT"],
  },
  {
    term: "PD",
    full: "Pharmacodynamics",
    emoji: "🔄",
    color: "#a78bfa",
    def: "What the drug does to the body/brain — the downstream biological adaptations. Includes autoreceptor desensitization, BDNF upregulation, glymphatic restoration, DMN normalization. PD changes take weeks and are why antidepressants have a delayed therapeutic onset.",
    related: ["PK", "Autoreceptor", "BDNF", "DMN"],
  },
  {
    term: "Wellbutrin",
    full: "Bupropion (Wellbutrin XL)",
    emoji: "💊",
    color: "#fbbf24",
    def: "A norepinephrine-dopamine reuptake inhibitor (NDRI) used here alongside Trintellix. Importantly, it is a potent CYP2D6 inhibitor (~2.1×), which boosts effective vortioxetine plasma levels. The combination addresses both serotonergic and dopaminergic/noradrenergic pathways.",
    related: ["CYP2D6", "Dopamine", "Norepinephrine"],
  },
  {
    term: "Transition Stress",
    full: "Antidepressant Switch Destabilization",
    emoji: "⚡",
    color: "#ef4444",
    def: "The temporary physiological and psychological destabilization that occurs during the crossover period when switching from Prozac to Trintellix. Encompasses norfluoxetine withdrawal, receptor rebalancing, GABA disinhibition lag, circadian disruption, and psychological adjustment. Peaks around days 21-28 and resolves by weeks 5-6.",
    related: ["Norfluoxetine", "SERT", "Autoreceptor", "GABA"],
  },
  {
    term: "Norfluoxetine Withdrawal",
    full: "Norfluoxetine Clearance Phase",
    emoji: "💊",
    color: "#f87171",
    def: "As fluoxetine's long-acting metabolite norfluoxetine clears (t½ ~14 days), SERT occupancy temporarily drops before Trintellix fully compensates. This creates a brief serotonergic dip during the transition — a key driver of the 'speed bump' period.",
    related: ["Norfluoxetine", "SERT", "Half-life", "Transition Stress"],
  },
  {
    term: "Receptor Rebalancing",
    full: "Serotonergic Receptor Profile Shift",
    emoji: "🔄",
    color: "#fb923c",
    def: "Prozac and Trintellix have very different receptor profiles — Prozac is SERT-only while Trintellix hits 5-HT1A, 5-HT1B, 5-HT3, 5-HT7, and more. During the overlap/gap, the serotonin system is in flux as receptors adjust to entirely new occupancy patterns.",
    related: ["SERT", "5-HT3", "5-HT1A", "5-HT7", "Transition Stress"],
  },
  {
    term: "GABA Disinhibition Lag",
    full: "GABAergic Disinhibition Ramp-Up",
    emoji: "🎵",
    color: "#f59e0b",
    def: "Trintellix's unique ability to block 5-HT3 receptors releases GABA's grip on glutamate, acetylcholine, and dopamine circuits — but this disinhibition takes 1-3 weeks to fully ramp up. During the lag, cognitive benefits are building but not yet stable.",
    related: ["GABA", "5-HT3", "Glutamate", "Transition Stress"],
  },
  {
    term: "Circadian Disruption",
    full: "Sleep Architecture Transition",
    emoji: "🌙",
    color: "#c084fc",
    def: "Switching SSRIs disrupts sleep architecture as serotonergic tone changes. Prozac and Trintellix affect 5-HT receptors differently — particularly 5-HT7, which controls circadian rhythm and REM sleep. During the transition, sleep stages are reshuffling toward a healthier pattern.",
    related: ["5-HT7", "Circadian Rhythm", "REM", "Glymphatic System", "Transition Stress"],
  },
  {
    term: "Psychological Adjustment",
    full: "Cognitive-Emotional Adaptation to Switch",
    emoji: "🧩",
    color: "#e879f9",
    def: "Beyond neurochemistry, switching medications triggers anxiety about the change itself — hypervigilance to every sensation, worry about whether the new drug will work, and nocebo effects where expectations of side effects create perceived symptoms. Awareness of this effect reduces its power.",
    related: ["Transition Stress", "DMN", "Nocebo"],
  },
];